cursor #ece1cf
cursor_text_color #d3c5aa

foreground            #ece1cf
background            #181308
selection_foreground  #2e330c
selection_background  #c5cb96
url_color             #dfb7fe

color0   #181308
color1   #ff728a
color2   #7ffe9d
color3   #ffdb72
color4   #cda0f1
color5   #5b3975
color6   #dfb7fe
color7   #f8efff
color8   #9f98a5
color9   #ff9faf
color10  #a5ffbb
color11  #ffe8a5
color12  #e4c2ff
color13  #e9cdff
color14  #f0deff
color15  #fcf8ff
